#pragma once

/* Shared config adapter for modules used by both AtomClaw and MimiClaw. */
#if CONFIG_DEVICE_ATOMCLAW
#include "atom_config.h"
#ifndef ATOM_TIMEZONE
#define ATOM_TIMEZONE "UTC0"
#endif

#define CFG_BUS_QUEUE_LEN           ATOM_BUS_QUEUE_LEN

#define CFG_SPIFFS_BASE             ATOM_SPIFFS_BASE
#define CFG_SPIFFS_MEMORY_DIR       ATOM_SPIFFS_MEMORY_DIR
#define CFG_MEMORY_FILE             ATOM_MEMORY_FILE

#define CFG_TIMEZONE                ATOM_TIMEZONE

#define CFG_SECRET_API_KEY          ATOM_SECRET_API_KEY
#define CFG_SECRET_MODEL            ATOM_SECRET_MODEL
#define CFG_SECRET_MODEL_PROVIDER   ATOM_SECRET_MODEL_PROVIDER
#define CFG_SECRET_PROXY_HOST       ATOM_SECRET_PROXY_HOST
#define CFG_SECRET_PROXY_PORT       ATOM_SECRET_PROXY_PORT
#define CFG_SECRET_SEARCH_KEY       ATOM_SECRET_SEARCH_KEY

#define CFG_LLM_DEFAULT_MODEL       ATOM_LLM_DEFAULT_MODEL
#define CFG_LLM_PROVIDER_DEFAULT    ATOM_LLM_PROVIDER_DEFAULT
#define CFG_LLM_API_URL             ATOM_LLM_API_URL
#define CFG_OPENAI_API_URL          ATOM_OPENAI_API_URL
#define CFG_LLM_API_VERSION         ATOM_LLM_API_VERSION
#define CFG_LLM_MAX_TOKENS          ATOM_LLM_MAX_TOKENS
#define CFG_LLM_STREAM_BUF_SIZE     ATOM_LLM_STREAM_BUF_SIZE
#define CFG_MAX_TOOL_CALLS          ATOM_MAX_TOOL_CALLS

#define CFG_NVS_LLM                 ATOM_NVS_LLM
#define CFG_NVS_PROXY               ATOM_NVS_PROXY
#define CFG_NVS_SEARCH              ATOM_NVS_SEARCH
#define CFG_NVS_KEY_API_KEY         ATOM_NVS_KEY_API_KEY
#define CFG_NVS_KEY_MODEL           ATOM_NVS_KEY_MODEL
#define CFG_NVS_KEY_PROVIDER        ATOM_NVS_KEY_PROVIDER
#define CFG_NVS_KEY_PROXY_HOST      ATOM_NVS_KEY_PROXY_HOST
#define CFG_NVS_KEY_PROXY_PORT      ATOM_NVS_KEY_PROXY_PORT
#else
#include "mimi_config.h"

#define CFG_BUS_QUEUE_LEN           MIMI_BUS_QUEUE_LEN

#define CFG_SPIFFS_BASE             MIMI_SPIFFS_BASE
#define CFG_SPIFFS_MEMORY_DIR       MIMI_SPIFFS_MEMORY_DIR
#define CFG_MEMORY_FILE             MIMI_MEMORY_FILE

#define CFG_TIMEZONE                MIMI_TIMEZONE

#define CFG_SECRET_API_KEY          MIMI_SECRET_API_KEY
#define CFG_SECRET_MODEL            MIMI_SECRET_MODEL
#define CFG_SECRET_MODEL_PROVIDER   MIMI_SECRET_MODEL_PROVIDER
#define CFG_SECRET_PROXY_HOST       MIMI_SECRET_PROXY_HOST
#define CFG_SECRET_PROXY_PORT       MIMI_SECRET_PROXY_PORT
#define CFG_SECRET_SEARCH_KEY       MIMI_SECRET_SEARCH_KEY

#define CFG_LLM_DEFAULT_MODEL       MIMI_LLM_DEFAULT_MODEL
#define CFG_LLM_PROVIDER_DEFAULT    MIMI_LLM_PROVIDER_DEFAULT
#define CFG_LLM_API_URL             MIMI_LLM_API_URL
#define CFG_OPENAI_API_URL          MIMI_OPENAI_API_URL
#define CFG_LLM_API_VERSION         MIMI_LLM_API_VERSION
#define CFG_LLM_MAX_TOKENS          MIMI_LLM_MAX_TOKENS
#define CFG_LLM_STREAM_BUF_SIZE     MIMI_LLM_STREAM_BUF_SIZE
#define CFG_MAX_TOOL_CALLS          MIMI_MAX_TOOL_CALLS

#define CFG_NVS_LLM                 MIMI_NVS_LLM
#define CFG_NVS_PROXY               MIMI_NVS_PROXY
#define CFG_NVS_SEARCH              MIMI_NVS_SEARCH
#define CFG_NVS_KEY_API_KEY         MIMI_NVS_KEY_API_KEY
#define CFG_NVS_KEY_MODEL           MIMI_NVS_KEY_MODEL
#define CFG_NVS_KEY_PROVIDER        MIMI_NVS_KEY_PROVIDER
#define CFG_NVS_KEY_PROXY_HOST      MIMI_NVS_KEY_PROXY_HOST
#define CFG_NVS_KEY_PROXY_PORT      MIMI_NVS_KEY_PROXY_PORT
#endif
